version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:13-alpine        # Imagem oficial do PostgreSQL (versão 13, Alpine para ser leve)
    container_name: meu_app_postgres # Nome do contêiner para fácil identificação
    restart: always                  # Sempre reiniciar o contêiner se ele parar
    environment:
      # Variáveis de ambiente para configurar o PostgreSQL
      # ATENÇÃO: Troque 'senha_super_secreta' por uma senha forte
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sativarisisv25
      POSTGRES_DB: sativar_isis
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      # Mapeia a porta 5432 do contêiner para a 5432 da sua máquina local
      # Isso permite que aplicações fora do Docker (como o Next.js) se conectem
      - "5432:5432"
    volumes:
      # Garante que os dados do banco de dados persistam mesmo se o contêiner for removido
      - postgres_data:/var/lib/postgresql/data
      # Monta o script de inicialização
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    
  # Serviço do Painel de Gerenciamento (Adminer)
  adminer:
    image: adminer                   # Imagem oficial do Adminer
    container_name: meu_app_adminer  # Nome do contêiner
    restart: always
    ports:
      # Mapeia a porta 8080 do contêiner para a 8080 da sua máquina
      # É aqui que você vai acessar o painel
      - "8080:8080"
    depends_on:
      # Garante que o serviço do Adminer só vai iniciar DEPOIS que o serviço do PostgreSQL estiver pronto
      - postgres

# Define o volume nomeado para persistir os dados do PostgreSQL
volumes:
  postgres_data: