version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres:15
    container_name: sativar-db
    restart: always
    environment:
      POSTGRES_USER: sativar_user
      POSTGRES_PASSWORD: sativar_password
      POSTGRES_DB: sativar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - sativar-network

  # React frontend application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sativar-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - API_KEY=${GEMINI_API_KEY}
      - DB_HOST=db
      - DB_USER=sativar_user
      - DB_PASSWORD=sativar_password
      - DB_NAME=sativar_db
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - sativar-network

volumes:
  postgres_data:

networks:
  sativar-network:
    driver: bridge